# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a60bf601ceff30745b838cd7b28a987a5da0e28c9ce69b1e9ddf4ae7a5c88eeada5a6142c10013faea88d49d8871845e3fda2c4b20dd41d6cde9931690086181

test:
  secret_key_base: 864fe709eff640f2d4c9d7dd0e26ccbf2eab7a7c87cafcea1bcaed4fd85d7e04443129deee04bbd3094165ba02a430bc1f19de08e4533e29e6491d39ba6ec15c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
